
setup_args:
  exp_dir_suffix: DEBUG_NDF_NOAVOID
  seed: 0

evaluator:
  pybullet_viz: False
  obj_class: mug
  num_trials: 200
  include_avoid_obj: True

model:
  type: VNN_NDF
  checkpoint: multi_category_weights.pth
  args:
    latent_dim: 256
    model_type: pointnet
    return_features: True
    sigmoid: True
    acts: all

optimizer:
  args:
    opt_iterations: 500
    rand_translate: False

query_pts:
  type: SPHERE
  args:
    n_pts: 500
    radius: 0.05


